export const sliderItems = [
  {
    id: 1,
    sale: "W BEAUTY",
    img: "https://wforwoman.gumlet.io/banner/1666696423Desktop%20banner-01.png",
    title: "SUMMER SALE",
    desc: "DON'T COMPROMISE ON STYLE! GET FLAT 30% OFF FOR NEW ARRIVALS.",
    bg: "f5fafd",
  },
  {
    id: 2,
    sale: "W BEAUTY",
    img: "https://wforwoman.gumlet.io/banner/1667536010w-4-nov-web Banner.jpg",
    title: "AUTUMN SALE",
    desc: "DON'T COMPROMISE ON STYLE! GET FLAT 30% OFF FOR NEW ARRIVALS.",
    bg: "f5fafd",
  },
  {
    id: 3,
    sale: "TRENDING NOW",
    img: "https://wforwoman.gumlet.io/banner/1666257525Beauty-banner%20Sep%20final-desktop.jpg",
    title: "WINTER SALE",
    desc: "DON'T COMPROMISE ON STYLE! GET FLAT 30% OFF FOR NEW ARRIVALS.",
    bg: "f5fafd",
  },
  {
    id: 4,
    sale: "CATEGORY TO BAG",
    img: "https://wforwoman.gumlet.io/banner/1667549208W-footwear-Web-Banner4.jpg",
    title: "WINTER SALE",
    desc: "DON'T COMPROMISE ON STYLE! GET FLAT 30% OFF FOR NEW ARRIVALS.",
    bg: "f5fafd",
  },
  {
    id: 5,
    sale: "FOLKSONG",
    img: "https://wforwoman.gumlet.io/banner/1667549429W-Jewel-Web-Banner.jpg",
    title: "WINTER SALE",
    desc: "DON'T COMPROMISE ON STYLE! GET FLAT 30% OFF FOR NEW ARRIVALS.",
    bg: "f5fafd",
  },
];

export const footWearCollectionImg = [
  {
    id: 1,
    img: "https://wforwoman.gumlet.io/footwearcollection/165399937321FEW9FW00045-04001.jpg",
  },
  {
    id: 2,
    img: "https://wforwoman.gumlet.io/footwearcollection/165399937322FEW9FW00205-04089.JPG",
  },
  {
    id: 3,
    img: "https://wforwoman.gumlet.io/footwearcollection/165399937322FEW9FW00122-04031.JPG",
  },
  {
    id: 4,
    img: "https://wforwoman.gumlet.io/footwearcollection/165399937321FEW9FW0064-04089.jpg",
  },
  {
    id: 5,
    img: "https://wforwoman.gumlet.io/footwearcollection/165399944822FEW9FW00080-04001.JPG",
  },
  {
    id: 6,
    img: "https://wforwoman.gumlet.io/footwearcollection/165399944821AUW9FW00086-04018.jpg",
  },
];

export const filterText = [
  "Catogory",
  "Price",
  "Color",
  "Size",
  "Material",
  "Insole Material",
  "Neck Type",
  "Sleeve",
  "Occasion",
  "Length",
  "Pattern",
  "Ornamentation",
  "Toe Type",
  "Toe Shape",
  "Heel Type",
  "Fastening & Back Details",
  "Closure",
];

export const filterTypes = [
  [
    "Bottom Wear",
    "Palazzos & Pants",
    "Churidar & Salwar",
    "Churidars & Salwars",
    "Drapewear",
    "Dupattas",
    "Flats",
    "Heels",
    "Kurtas",
    "Palazzos & Pants",
    "Sets & Dresses",
    "Shirts",
  ],
  [
    "Rs.0 to Rs.2000",
    "Rs.2000 to Rs.4000",
    "Rs.4000 to Rs.6000",
    "Rs.6000 to Rs.8000",
    "Rs.8000 to Rs.10000",
  ],
  [
    "White",
    "Beige",
    "Black",
    "Blue",
    "Brown",
    "Blush",
    "Coral",
    "Dark Green",
    "Dark Blue",
    "Ecru",
  ],
  ["FS", "XS", "S", "M", "L", "XL", "XXL"],
  ["Alloy", "Brass", "Fabric", "PU"],
  ["Leather", "Pu"],
  [
    "Boat Neck",
    "Collared - V",
    "Keyhole Neck",
    "Lapel Collar",
    "Mandarin Collar",
    "NA",
  ],
  [
    "3 / 4 Sleev",
    "Elbow Sleev",
    "Full Sleev",
    "Half Sleev",
    "Short Sleev",
    "Sleeveless",
  ],
  ["Casual", "Ethnic", "Festive", "Party"],
  ["Above Knee", "Ankle Length", "Calf Length", "Knee Length"],
  [
    "Abstract",
    "All Over Buti",
    "All Over Jaal",
    "Animal",
    "Checkered",
    "Closed",
    "Embroidered",
    "Floral",
    "Geometric",
    "Ikkat",
    "Laser Cut",
    "Paisley",
    "Polka Dots",
    "Printed",
    "Shibori",
    "Solid",
    "Striped",
    "Textured",
    "Tribal",
    "Tropical",
    "Woven Design",
  ],
  [
    "Bread",
    "Braids",
    "Cutwork/Filigree",
    "Dori Embroidery",
    "Dried Flowers",
    "Embroidery",
  ],
  ["Closed", "Open", "Pointed Toe"],
  ["Almond Toe", "Laser Cut", "Pointed Toe", "Round Toe", "Square Toe"],
  ["Block", "Block Heel", "Flat", "Stiletto", "Wedge"],
  ["Ankle Strap", "Slip-On"],
  ["Buckle", "Button", "Button & Key Hole", "Button Fly", "Buttons", "Hinged"],
];
